//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriesE_comAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AriesEcommerceEntities : DbContext
    {
        public AriesEcommerceEntities()
            : base("name=AriesEcommerceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<UserLogin> UserLogins { get; set; }
        public DbSet<UserType> UserTypes { get; set; }
        public DbSet<AddressDetail> AddressDetails { get; set; }
        public DbSet<Member> Members { get; set; }
        public DbSet<MemberContactPhone> MemberContactPhones { get; set; }
        public DbSet<ProductAvailability> ProductAvailabilities { get; set; }
        public DbSet<ProductCategory> ProductCategories { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<DistCreditLimit> DistCreditLimits { get; set; }
        public DbSet<DistributorStock> DistributorStocks { get; set; }
    }
}
