//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriesE_comAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistCreditLimit
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public string FirmName { get; set; }
    }
}
