//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriesE_comAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberContactPhone
    {
        public int ID { get; set; }
        public Nullable<int> PhoneNumberTypeID { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> MobileCountryCode { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<int> MemberPersonDetailID { get; set; }
    }
}
