//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriesE_comAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Nullable<System.DateTime> OrderPlacedDate { get; set; }
        public int OrderID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public int Quantity { get; set; }
        public Nullable<decimal> ShippingCost { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public string OrderStatus { get; set; }
        public Nullable<int> DistributerID { get; set; }
    }
}
