//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriesE_comAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductAvailability
    {
        public int ID { get; set; }
        public int ProductID { get; set; }
        public int InventoryQuantity { get; set; }
        public Nullable<int> AllocatedQuantity { get; set; }
        public Nullable<System.DateTime> InventoryQuantityUpdatedDate { get; set; }
        public Nullable<System.DateTime> AllocatedQuantityUpdatedDate { get; set; }
    }
}
